TRAIN:
  ENABLE: False
  DATASET: kinetics
  BATCH_SIZE: 16
  EVAL_PERIOD: 10
  CHECKPOINT_PERIOD: 1
  AUTO_RESUME: True
  #CHECKPOINT_FILE_PATH: path to the model to test
  CHECKPOINT_FILE_PATH: configs/PD/I3D_8x8_R50.pkl 
  CHECKPOINT_TYPE: caffe2
DATA:
  NUM_FRAMES: 8
  SAMPLING_RATE: 8
  TRAIN_JITTER_SCALES: [256, 320]
  TRAIN_CROP_SIZE: 224
  TEST_CROP_SIZE: 256
  INPUT_CHANNEL_NUM: [3]
  PATH_TO_DATA_DIR: data
RESNET:
  ZERO_INIT_FINAL_BN: True
  WIDTH_PER_GROUP: 64
  NUM_GROUPS: 1
  DEPTH: 50
  TRANS_FUNC: bottleneck_transform
  STRIDE_1X1: False
  NUM_BLOCK_TEMP_KERNEL: [[3], [4], [6], [3]]
NONLOCAL:
  LOCATION: [[[]], [[]], [[]], [[]]]
  GROUP: [[1], [1], [1], [1]]
  INSTANTIATION: softmax
BN:
  USE_PRECISE_STATS: True
  NUM_BATCHES_PRECISE: 200
SOLVER:
  BASE_LR: 0.1
  LR_POLICY: cosine
  MAX_EPOCH: 100
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1e-5
  WARMUP_EPOCHS: 10.0
  WARMUP_START_LR: 0.01
  OPTIMIZING_METHOD: sgd
MODEL:
  NUM_CLASSES: 11
  ARCH: i3d
  MODEL_NAME: ResNet
  LOSS_FUNC: cross_entropy
  DROPOUT_RATE: 0.5
TEST:
  ENABLE: True
  DATASET: kinetics
  BATCH_SIZE: 4
DATA_LOADER:
  NUM_WORKERS: 4
  PIN_MEMORY: True
TENSORBOARD:
  ENABLE: True
  MODEL_VIS:
    ENABLE: True
    MODEL_WEIGHTS: True
    ACTIVATIONS: True
    INPUT_VIDEO: True
    LAYER_LIST: ['s2/pathway0_res0','pathway0_pool','s3/pathway0_res0','s3/pathway0_res3','s4/pathway0_res0','s4/pathway0_res5','s5/pathway0_res0','s5/pathway0_res2','head/pathway0_avgpool']
    GRAD_CAM:
      ENABLE: True
      LAYER_LIST: ['s5/pathway0_res0/branch1']
      MODEL_VIS:
    ENABLE: True
    MODEL_WEIGHTS: True
    ACTIVATIONS: True
    INPUT_VIDEO: True
    LAYER_LIST: ['s3/pathway0_res0','s3/pathway0_res3','s4/pathway0_res0','s4/pathway0_res5','s5/pathway0_res0','s5/pathway0_res2','head/pathway0_avgpool', 'temporal_pool', 'region_pool', 'dummy_head']
    GRAD_CAM:
      ENABLE: True
      LAYER_LIST: ['temporal_pool']
DEMO:
    ENABLE: False
    INPUT_VIDEO: data/video113_256.mp4
    OUTPUT_FILE: data/demo.mp4
NUM_GPUS: 1
NUM_SHARDS: 1
RNG_SEED: 0
OUTPUT_DIR: .